import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/global/theme-provider";
import Navbar from "@/components/global/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
     <body className={inter.className}>
	<ThemeProvider
	  themes={[
	    "light",
	    "bumblebee",
	    "retro",
	    "synthwave",
	    "coffee",
	    "dark",
	    "forest",
	    "dracula",
	    "night",
	    "sunset",
	  ]}
	  >
	    <Navbar>
		{children}
	    </Navbar>
    	</ThemeProvider>
      </body>
    </html>
  );
}
